spring.application.name=ims

# PostgreSQL (Render IMS Database)
spring.datasource.url=jdbc:postgresql://dpg-d7n2nfok1i2s739ecs6g-a:5432/ims_fkai
spring.datasource.username=ims_fkai_user
spring.datasource.password=RwCMWhGg0xwSJOdFLDAFpqaOAnGao1dv

# Driver
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Optional tuning
spring.jpa.properties.hibernate.format_sql=true
